// Generated by gencpp from file hironx_ros_bridge/OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest.msg
// DO NOT EDIT!


#ifndef HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_ABSOLUTEFORCESENSORSERVICE_SETFORCEMOMENTOFFSETPARAMREQUEST_H
#define HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_ABSOLUTEFORCESENSORSERVICE_SETFORCEMOMENTOFFSETPARAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hironx_ros_bridge/OpenHRP_AbsoluteForceSensorService_forcemomentOffsetParam.h>

namespace hironx_ros_bridge
{
template <class ContainerAllocator>
struct OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_
{
  typedef OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> Type;

  OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_()
    : name()
    , i_param()  {
    }
  OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , i_param(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_forcemomentOffsetParam_<ContainerAllocator>  _i_param_type;
  _i_param_type i_param;




  typedef boost::shared_ptr< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_

typedef ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<std::allocator<void> > OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest;

typedef boost::shared_ptr< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest > OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequestPtr;
typedef boost::shared_ptr< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest const> OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hironx_ros_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hironx_ros_bridge': ['/home/pazeshun/test_ws/src/rtmros_hironx/hironx_ros_bridge/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08900466cdd7a5d34c4df86d3209a25f";
  }

  static const char* value(const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08900466cdd7a5d3ULL;
  static const uint64_t static_value2 = 0x4c4df86d3209a25fULL;
};

template<class ContainerAllocator>
struct DataType< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hironx_ros_bridge/OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest";
  }

  static const char* value(const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
OpenHRP_AbsoluteForceSensorService_forcemomentOffsetParam i_param\n\
\n\
================================================================================\n\
MSG: hironx_ros_bridge/OpenHRP_AbsoluteForceSensorService_forcemomentOffsetParam\n\
float64[3] force_offset\n\
float64[3] moment_offset\n\
float64[3] link_offset_centroid\n\
float64 link_offset_mass\n\
";
  }

  static const char* value(const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.i_param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "i_param: ";
    s << std::endl;
    Printer< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_forcemomentOffsetParam_<ContainerAllocator> >::stream(s, indent + "  ", v.i_param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_ABSOLUTEFORCESENSORSERVICE_SETFORCEMOMENTOFFSETPARAMREQUEST_H
