// Generated by gencpp from file hironx_ros_bridge/OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController.msg
// DO NOT EDIT!


#ifndef HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_IMPEDANCECONTROLLERSERVICE_WAITDELETINGIMPEDANCECONTROLLER_H
#define HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_IMPEDANCECONTROLLERSERVICE_WAITDELETINGIMPEDANCECONTROLLER_H

#include <ros/service_traits.h>


#include <hironx_ros_bridge/OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerRequest.h>
#include <hironx_ros_bridge/OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerResponse.h>


namespace hironx_ros_bridge
{

struct OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController
{

typedef OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerRequest Request;
typedef OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController
} // namespace hironx_ros_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController&) { return value(); }
};

template<>
struct DataType< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController > {
  static const char* value()
  {
    return "hironx_ros_bridge/OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController";
  }

  static const char* value(const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController&) { return value(); }
};


// service_traits::MD5Sum< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerRequest> should match 
// service_traits::MD5Sum< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController > 
template<>
struct MD5Sum< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController >::value();
  }
  static const char* value(const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerRequest> should match 
// service_traits::DataType< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController > 
template<>
struct DataType< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerRequest>
{
  static const char* value()
  {
    return DataType< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController >::value();
  }
  static const char* value(const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerResponse> should match 
// service_traits::MD5Sum< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController > 
template<>
struct MD5Sum< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController >::value();
  }
  static const char* value(const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerResponse> should match 
// service_traits::DataType< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController > 
template<>
struct DataType< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerResponse>
{
  static const char* value()
  {
    return DataType< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceController >::value();
  }
  static const char* value(const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_waitDeletingImpedanceControllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_IMPEDANCECONTROLLERSERVICE_WAITDELETINGIMPEDANCECONTROLLER_H
