// Generated by gencpp from file hironx_ros_bridge/OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse.msg
// DO NOT EDIT!


#ifndef HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_IMPEDANCECONTROLLERSERVICE_DELETEIMPEDANCECONTROLLERANDWAITRESPONSE_H
#define HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_IMPEDANCECONTROLLERSERVICE_DELETEIMPEDANCECONTROLLERANDWAITRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hironx_ros_bridge
{
template <class ContainerAllocator>
struct OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_
{
  typedef OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> Type;

  OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_()
    : operation_return(false)  {
    }
  OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_(const ContainerAllocator& _alloc)
    : operation_return(false)  {
  (void)_alloc;
    }



   typedef uint8_t _operation_return_type;
  _operation_return_type operation_return;




  typedef boost::shared_ptr< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_

typedef ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<std::allocator<void> > OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse;

typedef boost::shared_ptr< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse > OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponsePtr;
typedef boost::shared_ptr< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse const> OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hironx_ros_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hironx_ros_bridge': ['/home/pazeshun/test_ws/src/rtmros_hironx/hironx_ros_bridge/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dd59ee39c15084c92106411b8c3e8fc";
  }

  static const char* value(const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dd59ee39c15084cULL;
  static const uint64_t static_value2 = 0x92106411b8c3e8fcULL;
};

template<class ContainerAllocator>
struct DataType< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hironx_ros_bridge/OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse";
  }

  static const char* value(const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool operation_return\n\
\n\
";
  }

  static const char* value(const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.operation_return);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hironx_ros_bridge::OpenHRP_ImpedanceControllerService_deleteImpedanceControllerAndWaitResponse_<ContainerAllocator>& v)
  {
    s << indent << "operation_return: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.operation_return);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_IMPEDANCECONTROLLERSERVICE_DELETEIMPEDANCECONTROLLERANDWAITRESPONSE_H
