// Generated by gencpp from file hironx_ros_bridge/OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam.msg
// DO NOT EDIT!


#ifndef HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_ABSOLUTEFORCESENSORSERVICE_SETFORCEMOMENTOFFSETPARAM_H
#define HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_ABSOLUTEFORCESENSORSERVICE_SETFORCEMOMENTOFFSETPARAM_H

#include <ros/service_traits.h>


#include <hironx_ros_bridge/OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest.h>
#include <hironx_ros_bridge/OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamResponse.h>


namespace hironx_ros_bridge
{

struct OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam
{

typedef OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest Request;
typedef OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam
} // namespace hironx_ros_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam > {
  static const char* value()
  {
    return "bdfe08907291072f5ea378e404002e4b";
  }

  static const char* value(const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam&) { return value(); }
};

template<>
struct DataType< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam > {
  static const char* value()
  {
    return "hironx_ros_bridge/OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam";
  }

  static const char* value(const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam&) { return value(); }
};


// service_traits::MD5Sum< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest> should match 
// service_traits::MD5Sum< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam > 
template<>
struct MD5Sum< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam >::value();
  }
  static const char* value(const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest> should match 
// service_traits::DataType< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam > 
template<>
struct DataType< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest>
{
  static const char* value()
  {
    return DataType< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam >::value();
  }
  static const char* value(const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamResponse> should match 
// service_traits::MD5Sum< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam > 
template<>
struct MD5Sum< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam >::value();
  }
  static const char* value(const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamResponse> should match 
// service_traits::DataType< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam > 
template<>
struct DataType< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamResponse>
{
  static const char* value()
  {
    return DataType< ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParam >::value();
  }
  static const char* value(const ::hironx_ros_bridge::OpenHRP_AbsoluteForceSensorService_setForceMomentOffsetParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIRONX_ROS_BRIDGE_MESSAGE_OPENHRP_ABSOLUTEFORCESENSORSERVICE_SETFORCEMOMENTOFFSETPARAM_H
