// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __ImpedanceControllerService_hh__
#define __ImpedanceControllerService_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_ImpedanceControllerService
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_ImpedanceControllerService
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_ImpedanceControllerService
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE OpenHRP

_CORBA_MODULE_BEG

#ifndef __OpenHRP_mImpedanceControllerService__
#define __OpenHRP_mImpedanceControllerService__

  class ImpedanceControllerService;
  class _objref_ImpedanceControllerService;
  class _impl_ImpedanceControllerService;
  
  typedef _objref_ImpedanceControllerService* ImpedanceControllerService_ptr;
  typedef ImpedanceControllerService_ptr ImpedanceControllerServiceRef;

  class ImpedanceControllerService_Helper {
  public:
    typedef ImpedanceControllerService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_ImpedanceControllerService, ImpedanceControllerService_Helper> ImpedanceControllerService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_ImpedanceControllerService,ImpedanceControllerService_Helper > ImpedanceControllerService_out;

#endif

  // interface ImpedanceControllerService
  class ImpedanceControllerService {
  public:
    // Declarations for this interface type.
    typedef ImpedanceControllerService_ptr _ptr_type;
    typedef ImpedanceControllerService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_DblSequence3;

    class DblSequence3_var;

    class DblSequence3 : public _CORBA_Bounded_Sequence_w_FixSizeElement< ::CORBA::Double, 3, 8, 8 >  {
    public:
      typedef DblSequence3_var _var_type;
      inline DblSequence3() {}
      inline DblSequence3(const DblSequence3& _s)
        : _CORBA_Bounded_Sequence_w_FixSizeElement< ::CORBA::Double, 3, 8, 8 > (_s) {}

      inline DblSequence3(_CORBA_ULong _len, ::CORBA::Double* _val, _CORBA_Boolean _rel=0)
        : _CORBA_Bounded_Sequence_w_FixSizeElement< ::CORBA::Double, 3, 8, 8 > (_len, _val, _rel) {}

    

      inline DblSequence3& operator = (const DblSequence3& _s) {
        _CORBA_Bounded_Sequence_w_FixSizeElement< ::CORBA::Double, 3, 8, 8 > ::operator=(_s);
        return *this;
      }
    };

    class DblSequence3_out;

    class DblSequence3_var {
    public:
      inline DblSequence3_var() : _pd_seq(0) {}
      inline DblSequence3_var(DblSequence3* _s) : _pd_seq(_s) {}
      inline DblSequence3_var(const DblSequence3_var& _s) {
        if( _s._pd_seq )  _pd_seq = new DblSequence3(*_s._pd_seq);
        else              _pd_seq = 0;
      }
      inline ~DblSequence3_var() { if( _pd_seq )  delete _pd_seq; }
        
      inline DblSequence3_var& operator = (DblSequence3* _s) {
        if( _pd_seq )  delete _pd_seq;
        _pd_seq = _s;
        return *this;
      }
      inline DblSequence3_var& operator = (const DblSequence3_var& _s) {
        if( _s._pd_seq ) {
          if( !_pd_seq )  _pd_seq = new DblSequence3;
          *_pd_seq = *_s._pd_seq;
        } else if( _pd_seq ) {
          delete _pd_seq;
          _pd_seq = 0;
        }
        return *this;
      }
      inline ::CORBA::Double& operator [] (_CORBA_ULong _s) {
        return (*_pd_seq)[_s];
      }

    

      inline DblSequence3* operator -> () { return _pd_seq; }
      inline const DblSequence3* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
      inline operator DblSequence3& () const { return *_pd_seq; }
#else
      inline operator const DblSequence3& () const { return *_pd_seq; }
      inline operator DblSequence3& () { return *_pd_seq; }
#endif
        
      inline const DblSequence3& in() const { return *_pd_seq; }
      inline DblSequence3&       inout()    { return *_pd_seq; }
      inline DblSequence3*&      out() {
        if( _pd_seq ) { delete _pd_seq; _pd_seq = 0; }
        return _pd_seq;
      }
      inline DblSequence3* _retn() { DblSequence3* tmp = _pd_seq; _pd_seq = 0; return tmp; }
        
      friend class DblSequence3_out;
      
    private:
      DblSequence3* _pd_seq;
    };

    class DblSequence3_out {
    public:
      inline DblSequence3_out(DblSequence3*& _s) : _data(_s) { _data = 0; }
      inline DblSequence3_out(DblSequence3_var& _s)
        : _data(_s._pd_seq) { _s = (DblSequence3*) 0; }
      inline DblSequence3_out(const DblSequence3_out& _s) : _data(_s._data) {}
      inline DblSequence3_out& operator = (const DblSequence3_out& _s) {
        _data = _s._data;
        return *this;
      }
      inline DblSequence3_out& operator = (DblSequence3* _s) {
        _data = _s;
        return *this;
      }
      inline operator DblSequence3*&()  { return _data; }
      inline DblSequence3*& ptr()       { return _data; }
      inline DblSequence3* operator->() { return _data; }

      inline ::CORBA::Double& operator [] (_CORBA_ULong _i) {
        return (*_data)[_i];
      }

    

      DblSequence3*& _data;

    private:
      DblSequence3_out();
      DblSequence3_out& operator=(const DblSequence3_var&);
    };

    struct impedanceParam {
      typedef _CORBA_ConstrType_Variable_Var<impedanceParam> _var_type;

      
      ::CORBA::String_member name;

      ::CORBA::String_member base_name;

      ::CORBA::String_member target_name;

      ::CORBA::Double M_p;

      ::CORBA::Double D_p;

      ::CORBA::Double K_p;

      ::CORBA::Double M_r;

      ::CORBA::Double D_r;

      ::CORBA::Double K_r;

      DblSequence3 ref_force;

      DblSequence3 force_gain;

      DblSequence3 ref_moment;

      DblSequence3 moment_gain;

      ::CORBA::Double sr_gain;

      ::CORBA::Double avoid_gain;

      ::CORBA::Double reference_gain;

      ::CORBA::Double manipulability_limit;

    

      void operator>>= (cdrStream &) const;
      void operator<<= (cdrStream &);
    };

    typedef impedanceParam::_var_type impedanceParam_var;

    typedef _CORBA_ConstrType_Variable_OUT_arg< impedanceParam,impedanceParam_var > impedanceParam_out;

    static _dyn_attr const ::CORBA::TypeCode_ptr _tc_impedanceParam;

  
  };

  class _objref_ImpedanceControllerService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    ::CORBA::Boolean setImpedanceControllerParam(const ::OpenHRP::ImpedanceControllerService::impedanceParam& i_param);
    ::CORBA::Boolean getImpedanceControllerParam(const char* name, ::OpenHRP::ImpedanceControllerService::impedanceParam_out i_param);
    ::CORBA::Boolean deleteImpedanceController(const char* name);
    void waitDeletingImpedanceController(const char* name);
    ::CORBA::Boolean deleteImpedanceControllerAndWait(const char* name);

    inline _objref_ImpedanceControllerService()  { _PR_setobj(0); }  // nil
    _objref_ImpedanceControllerService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_ImpedanceControllerService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_ImpedanceControllerService(const _objref_ImpedanceControllerService&);
    _objref_ImpedanceControllerService& operator = (const _objref_ImpedanceControllerService&);
    // not implemented

    friend class ImpedanceControllerService;
  };

  class _pof_ImpedanceControllerService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_ImpedanceControllerService() : _OMNI_NS(proxyObjectFactory)(ImpedanceControllerService::_PD_repoId) {}
    virtual ~_pof_ImpedanceControllerService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_ImpedanceControllerService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_ImpedanceControllerService();

    virtual ::CORBA::Boolean setImpedanceControllerParam(const ::OpenHRP::ImpedanceControllerService::impedanceParam& i_param) = 0;
    virtual ::CORBA::Boolean getImpedanceControllerParam(const char* name, ::OpenHRP::ImpedanceControllerService::impedanceParam_out i_param) = 0;
    virtual ::CORBA::Boolean deleteImpedanceController(const char* name) = 0;
    virtual void waitDeletingImpedanceController(const char* name) = 0;
    virtual ::CORBA::Boolean deleteImpedanceControllerAndWait(const char* name) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ImpedanceControllerService;

_CORBA_MODULE_END



_CORBA_MODULE POA_OpenHRP
_CORBA_MODULE_BEG

  class ImpedanceControllerService :
    public virtual OpenHRP::_impl_ImpedanceControllerService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~ImpedanceControllerService();

    inline ::OpenHRP::ImpedanceControllerService_ptr _this() {
      return (::OpenHRP::ImpedanceControllerService_ptr) _do_this(::OpenHRP::ImpedanceControllerService::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_OpenHRP
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, const OpenHRP::ImpedanceControllerService::DblSequence3& _s);
void operator<<=(::CORBA::Any& _a, OpenHRP::ImpedanceControllerService::DblSequence3* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, OpenHRP::ImpedanceControllerService::DblSequence3*& _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const OpenHRP::ImpedanceControllerService::DblSequence3*& _sp);

extern void operator<<=(::CORBA::Any& _a, const OpenHRP::ImpedanceControllerService::impedanceParam& _s);
extern void operator<<=(::CORBA::Any& _a, OpenHRP::ImpedanceControllerService::impedanceParam* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, OpenHRP::ImpedanceControllerService::impedanceParam*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const OpenHRP::ImpedanceControllerService::impedanceParam*& _sp);

void operator<<=(::CORBA::Any& _a, OpenHRP::ImpedanceControllerService_ptr _s);
void operator<<=(::CORBA::Any& _a, OpenHRP::ImpedanceControllerService_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, OpenHRP::ImpedanceControllerService_ptr& _s);



inline void
OpenHRP::ImpedanceControllerService::_marshalObjRef(::OpenHRP::ImpedanceControllerService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_ImpedanceControllerService
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_ImpedanceControllerService
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_ImpedanceControllerService
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_ImpedanceControllerService
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_ImpedanceControllerService
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_ImpedanceControllerService
#endif

#endif  // __ImpedanceControllerService_hh__

